name: Test setup macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Install bats from source
        run: |
          git clone https://github.com/sstephenson/bats.git
          ./bats/install.sh /usr/local
      - name: Run setup macOS script
        run: yes y testuser testuser@example.com | ./scripts/setup-macos.sh
      - name: Run setup macOS test
        run: bats --tap test/setup-macos-test.sh
      - name: Done!
        run: echo "Done! 🚀"