name: Test setup macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install bats from source
        run: |
          git clone https://github.com/bats-core/bats-core.git
          sudo bash -c "bats-core/install.sh /usr/local"
      - name: Run setup macOS script
        run: |
          ./scripts/setup-macos.sh << ANSWERS
          y
          testuser
          testuser@example.com
          ANSWERS
      - name: Test setup macOS script
        run: |
          bats --tap test/setup-macos-test.sh
