name: Test setup macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ macos-10.15, macos-11, macos-12 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install bats from source
        run: |
          git clone https://github.com/bats-core/bats-core.git
          sudo bash -c "bats-core/install.sh /usr/local"
      - name: Run setup macOS script
        run: |
          ./src/setup-macos.sh << ANSWERS
          y
          y
          testuser
          testuser@example.com
          ANSWERS
      - name: Test setup macOS script
        run: |
          bats --tap test/setup-macos-test.sh
